# Generated by Django 2.2.1 on 2019-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
