# Generated by Django 2.2.1 on 2019-06-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0002_auto_20190628_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='p_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
