# Generated by Django 2.2.1 on 2019-06-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0003_productpage_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='p_img',
            field=models.ImageField(default='', upload_to='product_samples/%Y/%m/%d'),
        ),
    ]
