# Generated by Django 2.2.1 on 2019-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0004_auto_20190629_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='p_img',
            field=models.ImageField(default='default/', upload_to='product_samples/%Y/%m/%d/'),
        ),
    ]
