# Generated by Django 2.2.1 on 2019-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0006_auto_20190629_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='productid',
            name='image',
            field=models.ImageField(default='default/def.png', upload_to='pro_img/'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='p_price',
            field=models.IntegerField(default='200'),
        ),
    ]
