# Generated by Django 2.2.1 on 2019-06-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0007_auto_20190629_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productid',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productid',
            name='image',
            field=models.ImageField(blank=True, default='default/def.png', null=True, upload_to='pro_img/'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='p_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='king.ProductID'),
        ),
    ]
