# Generated by Django 2.2.1 on 2019-07-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0009_auto_20190702_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdesc',
            name='p_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
