# Generated by Django 2.2.1 on 2019-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0010_productdesc_p_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_title',
            new_name='p_id',
        ),
    ]
