# Generated by Django 2.2.1 on 2019-07-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0011_auto_20190702_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_description_short',
            new_name='description_short',
        ),
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_slides_img1',
            new_name='slides_img1',
        ),
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_slides_img2',
            new_name='slides_img2',
        ),
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_slides_img3',
            new_name='slides_img3',
        ),
        migrations.RenameField(
            model_name='productdesc',
            old_name='p_slides_img4',
            new_name='slides_img4',
        ),
    ]
