# Generated by Django 2.2.1 on 2019-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0012_auto_20190702_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
