# Generated by Django 2.2.1 on 2019-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0013_productpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='description_short',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productpage',
            name='image',
            field=models.ImageField(default='default/def_slides.jpg', upload_to='product_slides/'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='p_description_long1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productpage',
            name='p_description_long2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productpage',
            name='p_img1',
            field=models.ImageField(default='default/def_slides.jpg', upload_to='product_slides/'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='slides_img1',
            field=models.ImageField(default='default/def_slides.jpg', upload_to='product_slides/'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='slides_img2',
            field=models.ImageField(default='default/def_slides.jpg', upload_to='product_slides/'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='slides_img3',
            field=models.ImageField(default='default/def_slides.jpg', upload_to='product_slides/'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='slides_img4',
            field=models.ImageField(default='default/def_slides.jpg', upload_to='product_slides/'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.DeleteModel(
            name='ProductDesc',
        ),
    ]
