# Generated by Django 2.2.1 on 2019-07-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0014_auto_20190703_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpage',
            old_name='p_img1',
            new_name='image2',
        ),
    ]
