# Generated by Django 2.2.1 on 2019-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0016_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
